### ISSUE TITLE
Typo: 'Gwateway' should be 'Gateway'

### ISSUE THREAD

**Issue by AmineAouragh** [ksmin23/my-aws-cdk-examples#8]
There is a small typo in the title of [api-gateway/http-dynamodb-crud-api/README.md file](https://github.com/ksmin23/my-aws-cdk-examples/blob/main/api-gateway/http-dynamodb-crud-api/README.md) where 'Gwateway' should be 'Gateway'

**Comment by ksmin23** [comment]
Thanks for the information. I fixed it.
